import { useEffect, useState } from "react";
import { useChannel, usePresence } from "@ably-labs/react-hooks";

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const channelName = "some-channel-name";
  const [messages, setMessages] = useState([]);

  const [channel, ably] = useChannel(channelName, async (message) => {
    console.log("Received Ably message", message);
    setMessages((messages) => [...messages, message.data]);
  });

  const [presenceData, updateStatus] = usePresence("your-channel-name");

  const messageList = messages.map((message, index) => {
    return <li key={index}>{message.text}</li>;
  });

  const presentClients = presenceData.map((msg, index) => (
    <li key={index}>
      {msg.clientId}: {msg.data}
    </li>
  ));

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Present Clients</h1>
        <ul>{presentClients}</ul>
        <button
          onClick={() => {
            updateStatus("hello");
          }}
        >
          Update status to hello
        </button>

        <h1>Ably Message Data</h1>
        <button
          onClick={() => {
            channel.publish("test-message", { text: `${ably.auth.clientId} sent a message` });
          }}
        >
          Send A Message
        </button>
        <ul>{messageList}</ul>

      </main>

      <footer className={styles.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
